const questions = [
  "Describe una situación donde aplicar una regla estrictamente causaría más daño que beneficio. ¿Qué harías?",
  "¿Cómo actuarías si un superior directo del staff abusa de su rango?",
  "Explica cómo diferencias autoridad de autoritarismo.",
  "¿Qué harías si descubres corrupción interna dentro del staff?",
  "¿Cuándo es correcto ignorar una regla escrita?",
  "Relata una decisión impopular que tomarías para proteger la comunidad.",
  "¿Cómo manejarías un conflicto donde ambos lados tienen razón?",
  "¿Aceptarías perder tu rango por defender una decisión justa?",
  "¿Qué es más peligroso: un staff incompetente o uno con ego?",
  "¿Cómo detectarías favoritismo silencioso?",
  "¿Qué harías si el dueño del servidor rompe sus propias reglas?",
  "¿Cómo evitarías que el poder te cambie?",
  "¿Qué señales indican que un staff no está listo para autoridad?",
  "Explica un caso donde la neutralidad NO es correcta.",
  "¿Cómo actuarías ante una acusación sin pruebas claras?",
  "¿Qué pesa más: intención o resultado?",
  "¿Cómo manejarías presión externa para cambiar una sanción?",
  "¿Qué harías si una decisión correcta te hace perder apoyo?",
  "¿Cómo identificarías un abuso sin que haya denuncias?",
  "¿Qué es más dañino: inacción o exceso de sanciones?",
  "¿Cómo reaccionas cuando te equivocas públicamente?",
  "¿Qué harías si un amigo rompe una regla grave?",
  "¿Cómo mantienes criterio bajo estrés?",
  "¿Qué define a un líder dentro del staff?",
  "¿Cómo manejarías una crisis de reputación del servidor?",
  "¿Qué harías si la mayoría del staff está equivocada?",
  "¿Cómo evitarías conflictos de interés?",
  "¿Qué es justicia en una comunidad online?",
  "¿Cómo manejarías información confidencial?",
  "¿Qué harías si un staff filtra información interna?",
  "¿Cómo actuarías ante provocaciones constantes?",
  "¿Qué señales indican que alguien busca poder, no servir?",
  "¿Cómo reaccionarías ante una falsa acusación?",
  "¿Qué es lealtad a la comunidad?",
  "¿Cómo manejarías sanciones progresivas?",
  "¿Qué harías si un usuario influyente presiona decisiones?",
  "¿Cómo equilibras firmeza y empatía?",
  "¿Qué define un castigo ejemplar?",
  "¿Cómo actuarías si se cuestiona tu autoridad?",
  "¿Qué harías si detectas manipulación interna?",
  "¿Cómo evalúas credibilidad?",
  "¿Qué significa ser imparcial?",
  "¿Cómo reaccionarías ante errores del sistema?",
  "¿Qué harías si pierdes la confianza del staff?",
  "¿Cómo evitarías burnout en moderadores?",
  "¿Qué harías si una regla se vuelve obsoleta?",
  "¿Cómo manejarías sanciones inconsistentes?",
  "¿Qué define ética en moderación?",
  "¿Cómo reaccionas ante críticas públicas?",
  "¿Qué harías si una decisión justa genera odio?",
  "¿Cómo priorizas problemas?",
  "¿Qué harías si descubres favoritismo inconsciente?",
  "¿Cómo gestionas autoridad sin presencia?",
  "¿Qué define profesionalismo en Discord?",
  "¿Cómo manejarías denuncias falsas repetidas?",
  "¿Qué harías si el staff pierde respeto?",
  "¿Cómo actuarías si la comunidad se divide?",
  "¿Qué es liderazgo silencioso?",
  "¿Cómo manejas secretos del staff?",
  "¿Qué harías si rompes una regla sin querer?",
  "¿Cómo decides cuándo escalar un problema?",
  "¿Qué harías si un castigo correcto parece injusto?",
  "¿Cómo reaccionas ante presión del público?",
  "¿Qué define madurez para staff?",
  "¿Cómo evitarías abuso pasivo?",
  "¿Qué harías si un staff se cree intocable?",
  "¿Cómo equilibras rapidez y precisión?",
  "¿Qué define confianza?",
  "¿Cómo manejarías decisiones reversibles?",
  "¿Qué harías si una sanción genera precedentes peligrosos?",
  "¿Cómo identificas doble moral?",
  "¿Qué define integridad?",
  "¿Cómo actuarías ante conflictos privados?",
  "¿Qué harías si el staff se divide en bandos?",
  "¿Cómo evaluarías impacto a largo plazo?",
  "¿Qué define justicia restaurativa?",
  "¿Cómo manejarías disculpas públicas?",
  "¿Qué harías si el reglamento falla?",
  "¿Cómo manejarías silencio administrativo?",
  "¿Qué define autoridad moral?",
  "¿Cómo reaccionas ante traición interna?",
  "¿Qué harías si debes tomar una decisión sin toda la info?",
  "¿Cómo manejarías favoritismo estructural?",
  "¿Qué define imparcialidad real?",
  "¿Cómo actuarías ante sabotaje interno?",
  "¿Qué harías si el error fue tuyo?",
  "¿Cómo equilibras reglas y humanidad?",
  "¿Qué define vocación de servicio?",
  "¿Cómo manejarías pérdida de credibilidad?",
  "¿Qué harías si el poder te tienta?",
  "¿Cómo reaccionarías ante renuncias masivas?",
  "¿Qué define respeto genuino?",
  "¿Cómo manejarías decisiones irreversibles?",
  "¿Qué harías si detectas manipulación emocional?",
  "¿Cómo actuarías bajo crisis extrema?"
];
